DROP TABLE DEVICES;
DROP TABLE USERS;
DROP TABLE ROLES;

CREATE TABLE ROLES
(
    ROLE_ID     INT             NOT NULL    AUTO_INCREMENT,
    NAME        VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS
(
    USER_ID     INT             NOT NULL    AUTO_INCREMENT,
    ROLE_ID     INT             NOT NULL,
    EMAIL       VARCHAR(320)    NOT NULL,
    PASSWORD    VARCHAR(255)    NOT NULL,
    FNAME       VARCHAR(255)    NOT NULL,
    LNAME       VARCHAR(255)    NOT NULL,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE DEVICES
(
    DEVICE_ID   INT             NOT NULL    AUTO_INCREMENT,
    USER_ID     INT,
    KEY         INT             NOT NULL,
    NAME        VARCHAR(255)    NOT NULL,
    ACTIV_TIME  DATETIME,
    PRIMARY KEY (DEVICE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Initialize roles

INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('ASSOCIATE');
INSERT INTO ROLES (NAME) VALUES ('MEMBER');

-- Initialize default admin account

INSERT INTO USERS (ROLE_ID, EMAIL, PASSWORD, FNAME, LNAME) VALUES (1, 'admin@admin.com', '$2y$10$Opbh8vrV7j82MD36tLzrCudLDQ5.MvVf3WjXL9FA3ctDxp3NYVXam', 'Christian', 'Westbrook');
